#!/usr/bin/env python3
"""
audit_symbols.py — Run after first failed build to see every XDK symbol
the game references. Produces a prioritized list and generates empty stub
skeletons for any symbol not yet implemented.

Usage:
    python3 audit_symbols.py              # scan src/ for xdk_ references
    python3 audit_symbols.py --from-map   # scan linker map (more accurate)
"""

import sys
import os
import re
import glob
from collections import Counter

SRC_DIR      = "./src"
STUBS_DIR    = "./runtime/stubs"
XENIA_KERNEL = "./xenia/src/xenia/kernel"

def find_all_xdk_calls():
    """Grep the generated source for anything that looks like an external XDK call."""
    calls = Counter()
    pattern = re.compile(r'\b(xdk_\w+|XNui\w+|KIN\w+)\s*\(')

    for path in glob.glob(f"{SRC_DIR}/**/*.cpp", recursive=True):
        with open(path, encoding="utf-8", errors="ignore") as f:
            for line in f:
                for match in pattern.finditer(line):
                    calls[match.group(1)] += 1
    return calls

def find_implemented_stubs():
    """Find every extern "C" void xdk_X already written in stubs/."""
    implemented = set()
    pattern = re.compile(r'extern\s+"C"\s+void\s+(xdk_\w+)\s*\(')
    for path in glob.glob(f"{STUBS_DIR}/**/*.cpp", recursive=True):
        with open(path, encoding="utf-8", errors="ignore") as f:
            for line in f:
                m = pattern.search(line)
                if m:
                    implemented.add(m.group(1))
    return implemented

def xenia_has_impl(func_name):
    """Quick grep: does Xenia have this symbol anywhere in kernel/?"""
    # Strip xdk_ prefix for the search
    name = func_name.replace("xdk_", "")
    for path in glob.glob(f"{XENIA_KERNEL}/**/*.cc", recursive=True):
        try:
            with open(path, encoding="utf-8", errors="ignore") as f:
                if name in f.read():
                    return path
        except:
            pass
    return None

def main():
    print("=== Kinect Sports XDK Symbol Audit ===\n")

    calls       = find_all_xdk_calls()
    implemented = find_implemented_stubs()

    missing = {k: v for k, v in calls.items() if k not in implemented}
    missing_sorted = sorted(missing.items(), key=lambda x: -x[1])

    print(f"Total unique XDK symbols referenced: {len(calls)}")
    print(f"Already implemented:                 {len(implemented)}")
    print(f"Missing stubs:                       {len(missing)}\n")

    kinect_symbols = [(k, v) for k, v in missing_sorted
                      if any(x in k for x in ["Kinect", "NUI", "XNui", "KIN_", "Nui"])]
    other_symbols  = [(k, v) for k, v in missing_sorted
                      if k not in dict(kinect_symbols)]

    if kinect_symbols:
        print("--- KINECT SYMBOLS (need special handling) ---")
        for sym, count in kinect_symbols:
            xenia_ref = xenia_has_impl(sym)
            ref_str = f" [xenia: {os.path.basename(xenia_ref)}]" if xenia_ref else " [no xenia ref]"
            print(f"  {sym:50s}  calls={count}{ref_str}")
        print()

    print("--- MISSING STUBS (by call frequency) ---")
    for sym, count in other_symbols[:50]:
        xenia_ref = xenia_has_impl(sym)
        ref_str = f" [xenia: {os.path.basename(xenia_ref)}]" if xenia_ref else " [no xenia ref]"
        print(f"  {sym:50s}  calls={count}{ref_str}")

    if len(other_symbols) > 50:
        print(f"  ... and {len(other_symbols) - 50} more")

    # Generate stub skeletons file for agent to fill in
    output_path = f"{STUBS_DIR}/generated_stubs.cpp"
    with open(output_path, "w") as out:
        out.write('#include "stubs.h"\n\n')
        out.write('// AUTO-GENERATED by audit_symbols.py — fill these in!\n')
        out.write('// Reference: xenia/src/xenia/kernel/ for each symbol\n\n')
        for sym, count in other_symbols:
            out.write(f'// Called {count}x in game source\n')
            out.write(f'extern "C"\nvoid {sym}(PPCContext* ctx, uint8_t* rdmem) {{\n')
            out.write(f'    LOG_STUB("{sym[4:]}");\n')
            out.write(f'    STUB_RETURN_ZERO(ctx);\n')
            out.write(f'}}\n\n')

    print(f"\nGenerated stub skeletons -> {output_path}")
    print("Agent should fill these in using Xenia as reference.")

if __name__ == "__main__":
    main()
