#pragma once

// ppc_recomp_shared.h is generated by XenonRecomp and defines:
//   PPCContext  (the CPU register struct — ctx is passed by reference)
//   PPC_FUNC_IMPL, PPC_EXTERN_FUNC, PPC_WEAK_FUNC macros
//   PPC_LOAD_U32, PPC_STORE_U32, PPC_LOAD_U64, PPC_STORE_U64 memory macros
//   uint8_t* base  (the flat guest memory buffer, used in all generated code)
//
// This file must be on the include path. It lives in src/ alongside the
// generated game code. All runtime and stub files include THIS header,
// which pulls in the shared definitions.
#include "ppc_recomp_shared.h"

#include "memory.h"
#include <cstdio>
#include <cstdint>
#include <cstring>

// ---------------------------------------------------------------------------
// guest_str — read a C string from guest address space
// ---------------------------------------------------------------------------
inline const char* guest_str(uint32_t addr) {
    if (addr == 0) return "(null)";
    return reinterpret_cast<const char*>(g_memory + addr);
}

// ---------------------------------------------------------------------------
// Entry point — name must match what XenonRecomp emitted for the XEX entry.
// ---------------------------------------------------------------------------
extern "C" void _xstart(PPCContext& ctx, uint8_t* base);
