#pragma once
#include "host.h"
#include <cstdio>
#include <cstring>

// ============================================================
// STUB CONVENTIONS — read this before implementing anything
// ============================================================
//
// XenonRecomp calling convention (confirmed from generated source):
//   PPC_EXTERN_FUNC(__imp__FunctionName) expands to:
//     void __imp__FunctionName(PPCContext& ctx, uint8_t* base)
//
//   ctx  — CPU register file, passed BY REFERENCE (not pointer)
//   base — the flat 512MB guest memory buffer (= g_memory)
//
// PowerPC ABI:
//   Integer args:   ctx.r3 (arg1), ctx.r4, ctx.r5 ... ctx.r10
//   Integer return: ctx.r3.u64 = value
//   Float args:     ctx.f1 (arg1) ... ctx.f13
//   Float return:   ctx.f1
//
// Memory helpers (from memory.h):
//   mem_read32(addr)       — big-endian u32 read from guest address
//   mem_write32(addr, v)   — big-endian u32 write to guest address
//   guest_to_host(addr)    — guest uint32 address -> host void*
//   guest_str(addr)        — guest address -> const char*
//
// PPC_EXTERN_FUNC is defined in ppc_recomp_shared.h (generated by XenonRecomp).
// Always use it for stubs so the linker resolves them against the import table.
//
// Example stub:
//   PPC_EXTERN_FUNC(__imp__RtlEnterCriticalSection) {
//       // r3 = CRITICAL_SECTION* (no-op is fine for now)
//       ctx.r3.u64 = 0;
//   }

#define STUB_LOG(name) \
    fprintf(stderr, "[STUB] " name "\n")
